// swift-tools-version: 5.10
import PackageDescription
// The macOS app is generated by Tuist (apps/mac/Project.swift, sources in Sources/ProjectXApp); this package holds the core library and its tests.
let package = Package(
    name: "PROJECTX", platforms: [.macOS(.v14)],
    products: [.library(name: "ProjectXCore", targets: ["ProjectXCore"])],
    dependencies: [.package(url: "https://github.com/groue/GRDB.swift.git", exact: "7.8.0")],
    targets: [.target(name: "ProjectXCore", dependencies: [.product(name: "GRDB", package: "GRDB.swift")]),
              .testTarget(name: "ProjectXCoreTests", dependencies: ["ProjectXCore", .product(name: "GRDB", package: "GRDB.swift")])])
