// Generated by scripts/generate-menubar-icon.py from AppIcon.icon. Do not hand-edit.
// Source loop-front-light.svg SHA-256: 37f1a3f9a61fd53aaa7dbc2c759aef9d2c7f1e0ad23cdaefb2c17eb1a10379ed
import AppKit

/// Native vector template: no Bundle.module lookup or packaging resource dependency.
/// Saved crossed-loop geometry; the original center is solid online, hollow offline.
@MainActor
enum YorozuMenuBarIcon {
    static let size = NSSize(width: 18, height: 18)
    static let connected = makeImage(connected: true)
    static let offline = makeImage(connected: false)

    static func image(connected: Bool) -> NSImage { connected ? self.connected : offline }

    private static func makeImage(connected: Bool) -> NSImage {
        let image = NSImage(size: size, flipped: true) { rect in
            guard let context = NSGraphicsContext.current?.cgContext else { return false }
            draw(in: context, rect: rect, connected: connected)
            return true
        }
        image.isTemplate = true
        return image
    }

    /// Internal for the standalone rendering/geometry regression check.
    static func draw(in context: CGContext, rect: CGRect, connected: Bool) {
        context.saveGState()
        defer { context.restoreGState() }
        context.translateBy(x: rect.minX, y: rect.minY)
        context.scaleBy(x: rect.width / 1024, y: rect.height / 1024)
        // Reduced template coverage also distinguishes offline at 1x, where the hollow
        // center alone is subpixel. macOS still owns the foreground tint.
        context.setFillColor(NSColor.black.withAlphaComponent(connected ? 1 : 0.55).cgColor)
        for angle in [-CGFloat.pi / 4, CGFloat.pi / 4] {
            context.saveGState()
            context.translateBy(x: 512, y: 512)
            context.rotate(by: angle)
            context.translateBy(x: -170, y: -365.5)
            context.addPath(loopPath())
            context.fillPath()
            context.restoreGState()
        }
        // The paper ring is negative space in a monochrome template, not a white paint.
        context.setBlendMode(.clear)
        context.fillEllipse(in: CGRect(x: 407.875, y: 407.875, width: 208.25, height: 208.25))
        context.setBlendMode(.normal)
        let center = CGRect(x: 446.125, y: 446.125, width: 131.75, height: 131.75)
        context.fillEllipse(in: center)
        if !connected {
            context.setBlendMode(.clear)
            // Hollow the existing center; keep both brand loops intact in either state.
            context.fillEllipse(in: center.insetBy(dx: 30, dy: 30))
        }
    }

    private static func loopPath() -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 303.875, y: 365.5))
        path.addLine(to: CGPoint(x: 303.875, y: 471.1269590854645))
        path.addCurve(to: CGPoint(x: 302.65605407534696, y: 553.1854462809016), control1: CGPoint(x: 303.875, y: 518.4600770004806), control2: CGPoint(x: 303.68541775713044, y: 534.9166190372978))
        path.addCurve(to: CGPoint(x: 294.95221173157654, y: 605.5372785500278), control1: CGPoint(x: 301.4603342817083, y: 574.4067101823974), control2: CGPoint(x: 299.1385739867525, y: 590.2727614431085))
        path.addCurve(to: CGPoint(x: 292.8209301102223, y: 612.7548603672317), control1: CGPoint(x: 294.29433491571183, y: 607.936060905185), control2: CGPoint(x: 293.5854303655931, y: 610.3370699272028))
        path.addLine(to: CGPoint(x: 293.3186843320705, y: 611.2904942825089))
        path.addCurve(to: CGPoint(x: 220.29049428250886, y: 684.3186843320705), control1: CGPoint(x: 280.9656146461956, y: 645.2301172742958), control2: CGPoint(x: 254.23011727429582, y: 671.9656146461956))
        path.addLine(to: CGPoint(x: 219.7949847086483, y: 684.4990359021924))
        path.addLine(to: CGPoint(x: 219.30495024537765, y: 684.6937732931613))
        path.addCurve(to: CGPoint(x: 186.590764900313, y: 693.6688615041337), control1: CGPoint(x: 207.68573630252405, y: 689.3111942664486), control2: CGPoint(x: 196.75431305064706, y: 692.1716016336221))
        path.addCurve(to: CGPoint(x: 170.0, y: 694.875), control1: CGPoint(x: 180.0160666270684, y: 694.6374240316726), control2: CGPoint(x: 175.6125221505138, y: 694.875))
        path.addCurve(to: CGPoint(x: 153.409235099687, y: 693.6688615041337), control1: CGPoint(x: 164.3874778494862, y: 694.875), control2: CGPoint(x: 159.9839333729316, y: 694.6374240316726))
        path.addCurve(to: CGPoint(x: 120.69504975462235, y: 684.6937732931613), control1: CGPoint(x: 143.24568694935294, y: 692.1716016336221), control2: CGPoint(x: 132.31426369747595, y: 689.3111942664486))
        path.addLine(to: CGPoint(x: 120.2050152913517, y: 684.4990359021924))
        path.addLine(to: CGPoint(x: 119.70950571749114, y: 684.3186843320705))
        path.addCurve(to: CGPoint(x: 46.68131566792951, y: 611.2904942825088), control1: CGPoint(x: 85.76988272570426, y: 671.9656146461956), control2: CGPoint(x: 59.034385353804346, y: 645.2301172742957))
        path.addLine(to: CGPoint(x: 47.17906988977759, y: 612.7548603672315))
        path.addCurve(to: CGPoint(x: 45.04778826842346, y: 605.537278550028), control1: CGPoint(x: 46.41456963440786, y: 610.337069927206), control2: CGPoint(x: 45.705665084287084, y: 607.9360609051813))
        path.addCurve(to: CGPoint(x: 37.34394592465304, y: 553.1854462809016), control1: CGPoint(x: 40.86142601324751, y: 590.2727614431085), control2: CGPoint(x: 38.53966571829172, y: 574.4067101823975))
        path.addCurve(to: CGPoint(x: 36.125, y: 471.1269590854645), control1: CGPoint(x: 36.31458224286952, y: 534.9166190372969), control2: CGPoint(x: 36.125, y: 518.4600770004824))
        path.addLine(to: CGPoint(x: 36.125, y: 259.8730409145355))
        path.addCurve(to: CGPoint(x: 37.34394592465304, y: 177.81455371909837), control1: CGPoint(x: 36.125, y: 212.53992299951878), control2: CGPoint(x: 36.31458224286954, y: 196.08338096270273))
        path.addCurve(to: CGPoint(x: 45.047788268423446, y: 125.46272144997208), control1: CGPoint(x: 38.53966571829172, y: 156.5932898176023), control2: CGPoint(x: 40.861426013247474, y: 140.72723855689165))
        path.addCurve(to: CGPoint(x: 47.17906988977759, y: 118.24513963276851), control1: CGPoint(x: 45.705665084287304, y: 123.06393909481788), control2: CGPoint(x: 46.41456963440776, y: 120.66293007279424))
        path.addLine(to: CGPoint(x: 46.6813156679295, y: 119.70950571749114))
        path.addCurve(to: CGPoint(x: 119.70950571749114, y: 46.6813156679295), control1: CGPoint(x: 59.034385353804296, y: 85.76988272570433), control2: CGPoint(x: 85.76988272570435, y: 59.03438535380428))
        path.addLine(to: CGPoint(x: 120.20501529135234, y: 46.50096409780728))
        path.addLine(to: CGPoint(x: 120.69504975462235, y: 46.306226706838736))
        path.addCurve(to: CGPoint(x: 153.409235099687, y: 37.33113849586634), control1: CGPoint(x: 132.31426369747595, y: 41.68880573355131), control2: CGPoint(x: 143.2456869493525, y: 38.828398366377996))
        path.addCurve(to: CGPoint(x: 170.0, y: 36.125), control1: CGPoint(x: 159.98393337293223, y: 36.36257596832734), control2: CGPoint(x: 164.38747784948595, y: 36.125))
        path.addCurve(to: CGPoint(x: 186.590764900313, y: 37.33113849586634), control1: CGPoint(x: 175.61252215051405, y: 36.125), control2: CGPoint(x: 180.01606662706777, y: 36.36257596832734))
        path.addCurve(to: CGPoint(x: 219.30495024537765, y: 46.306226706838736), control1: CGPoint(x: 196.7543130506475, y: 38.828398366377996), control2: CGPoint(x: 207.68573630252405, y: 41.68880573355131))
        path.addLine(to: CGPoint(x: 219.79498470864766, y: 46.50096409780728))
        path.addLine(to: CGPoint(x: 220.29049428250886, y: 46.68131566792951))
        path.addCurve(to: CGPoint(x: 293.31868433207046, y: 119.70950571749114), control1: CGPoint(x: 254.2301172742957, y: 59.0343853538043), control2: CGPoint(x: 280.96561464619566, y: 85.76988272570424))
        path.addLine(to: CGPoint(x: 292.82093011022243, y: 118.24513963276856))
        path.addCurve(to: CGPoint(x: 294.95221173157665, y: 125.46272144997235), control1: CGPoint(x: 293.58543036559206, y: 120.66293007279351), control2: CGPoint(x: 294.29433491571234, y: 123.06393909481649))
        path.addCurve(to: CGPoint(x: 302.656054075347, y: 177.81455371909837), control1: CGPoint(x: 299.13857398675253, y: 140.7272385568915), control2: CGPoint(x: 301.4603342817083, y: 156.5932898176024))
        path.addCurve(to: CGPoint(x: 303.875, y: 259.8730409145355), control1: CGPoint(x: 303.68541775713044, y: 196.08338096270208), control2: CGPoint(x: 303.875, y: 212.53992299951938))
        path.addLine(to: CGPoint(x: 303.875, y: 365.5))
        path.closeSubpath()
        path.move(to: CGPoint(x: 376.125, y: 365.5))
        path.addLine(to: CGPoint(x: 376.125, y: 259.8730409145355))
        path.addCurve(to: CGPoint(x: 374.7916367994568, y: 173.75004820758653), control1: CGPoint(x: 376.125, y: 211.00715317006876), control2: CGPoint(x: 375.928161481137, y: 193.92073562851274))
        path.addCurve(to: CGPoint(x: 364.6293152668533, y: 106.35346340748586), control1: CGPoint(x: 373.3277390972004, y: 147.7692459915084), control2: CGPoint(x: 370.2847500091523, y: 126.97458387171592))
        path.addCurve(to: CGPoint(x: 361.7091936600144, y: 96.46281548922514), control1: CGPoint(x: 363.724842062171, y: 103.05552933870001), control2: CGPoint(x: 362.75283502367563, y: 99.76341100132832))
        path.addLine(to: CGPoint(x: 361.4759939292648, y: 95.72530353201813))
        path.addLine(to: CGPoint(x: 361.21143943816645, y: 94.99844940450288))
        path.addCurve(to: CGPoint(x: 245.00155059549712, y: -21.211439438166472), control1: CGPoint(x: 341.55398306298326, y: 40.99028177357858), control2: CGPoint(x: 299.00971822642146, y: -1.5539830629832245))
        path.addLine(to: CGPoint(x: 232.646022439003, y: 12.734938114881516))
        path.addLine(to: CGPoint(x: 245.98709463262833, y: -20.836350477075705))
        path.addCurve(to: CGPoint(x: 197.12074435724202, y: -34.14740396714596), control1: CGPoint(x: 229.01980067419328, y: -27.579073295412062), control2: CGPoint(x: 212.67488646343082, y: -31.856019850953665))
        path.addCurve(to: CGPoint(x: 180.09687318394515, y: -35.87355623001488), control1: CGPoint(x: 191.11985990478175, y: -35.031434164607106), control2: CGPoint(x: 185.47206600292174, y: -35.583558786883806))
        path.addCurve(to: CGPoint(x: 170.0, y: -36.125), control1: CGPoint(x: 176.33512831089297, y: -36.076506418340266), control2: CGPoint(x: 173.67550359372538, y: -36.125))
        path.addCurve(to: CGPoint(x: 159.90312681605485, y: -35.87355623001488), control1: CGPoint(x: 166.32449640627462, y: -36.125), control2: CGPoint(x: 163.66487168910703, y: -36.076506418340266))
        path.addCurve(to: CGPoint(x: 142.87925564275798, y: -34.14740396714596), control1: CGPoint(x: 154.52793399707826, y: -35.583558786883806), control2: CGPoint(x: 148.88014009521825, y: -35.031434164607106))
        path.addCurve(to: CGPoint(x: 94.01290536737167, y: -20.836350477075705), control1: CGPoint(x: 127.3251135365692, y: -31.85601985095367), control2: CGPoint(x: 110.9801993258067, y: -27.579073295412048))
        path.addLine(to: CGPoint(x: 107.35397756099701, y: 12.734938114881516))
        path.addLine(to: CGPoint(x: 94.99844940450288, y: -21.21143943816648))
        path.addCurve(to: CGPoint(x: -21.21143943816648, y: 94.99844940450288), control1: CGPoint(x: 40.99028177357848, y: -1.5539830629832068), control2: CGPoint(x: -1.5539830629832103, y: 40.990281773578474))
        path.addLine(to: CGPoint(x: -21.47599392926481, y: 95.72530353201813))
        path.addLine(to: CGPoint(x: -21.709193660014556, y: 96.46281548922546))
        path.addCurve(to: CGPoint(x: -24.62931526685331, y: 106.3534634074859), control1: CGPoint(x: -22.752835023675004, y: 99.76341100132642), control2: CGPoint(x: -23.72484206217164, y: 103.0555293387025))
        path.addCurve(to: CGPoint(x: -34.79163679945677, y: 173.7500482075865), control1: CGPoint(x: -30.284750009152376, y: 126.9745838717164), control2: CGPoint(x: -33.32773909720037, y: 147.76924599150806))
        path.addCurve(to: CGPoint(x: -36.125, y: 259.8730409145355), control1: CGPoint(x: -35.928161481136975, y: 193.9207356285121), control2: CGPoint(x: -36.125, y: 211.00715317006996))
        path.addLine(to: CGPoint(x: -36.125, y: 471.1269590854645))
        path.addCurve(to: CGPoint(x: -34.79163679945677, y: 557.2499517924135), control1: CGPoint(x: -36.125, y: 519.9928468299295), control2: CGPoint(x: -35.92816148113697, y: 537.0792643714881))
        path.addCurve(to: CGPoint(x: -24.62931526685331, y: 624.646536592514), control1: CGPoint(x: -33.327739097200364, y: 583.2307540084921), control2: CGPoint(x: -30.284750009152415, y: 604.0254161282834))
        path.addCurve(to: CGPoint(x: -21.709193660014527, y: 634.5371845107746), control1: CGPoint(x: -23.72484206217192, y: 627.9444706612965), control2: CGPoint(x: -22.752835023674436, y: 631.2365889986754))
        path.addLine(to: CGPoint(x: -21.475993929264913, y: 635.2746964679816))
        path.addLine(to: CGPoint(x: -21.211439438166472, y: 636.0015505954971))
        path.addCurve(to: CGPoint(x: 94.99844940450288, y: 752.2114394381665), control1: CGPoint(x: -1.5539830629832672, y: 690.0097182264215), control2: CGPoint(x: 40.99028177357859, y: 732.5539830629833))
        path.addLine(to: CGPoint(x: 107.35397756099701, y: 718.2650618851185))
        path.addLine(to: CGPoint(x: 94.01290536737167, y: 751.8363504770757))
        path.addCurve(to: CGPoint(x: 142.87925564275798, y: 765.1474039671459), control1: CGPoint(x: 110.9801993258067, y: 758.5790732954121), control2: CGPoint(x: 127.32511353656876, y: 762.8560198509535))
        path.addCurve(to: CGPoint(x: 159.90312681605485, y: 766.8735562300149), control1: CGPoint(x: 148.88014009522013, y: 766.0314341646074), control2: CGPoint(x: 154.52793399707664, y: 766.5835587868837))
        path.addCurve(to: CGPoint(x: 170.0, y: 767.125), control1: CGPoint(x: 163.66487168910663, y: 767.0765064183403), control2: CGPoint(x: 166.32449640627655, y: 767.125))
        path.addCurve(to: CGPoint(x: 180.09687318394515, y: 766.8735562300149), control1: CGPoint(x: 173.67550359372345, y: 767.125), control2: CGPoint(x: 176.33512831089337, y: 767.0765064183403))
        path.addCurve(to: CGPoint(x: 197.12074435724202, y: 765.1474039671459), control1: CGPoint(x: 185.47206600292336, y: 766.5835587868837), control2: CGPoint(x: 191.11985990477987, y: 766.0314341646074))
        path.addCurve(to: CGPoint(x: 245.98709463262833, y: 751.8363504770757), control1: CGPoint(x: 212.67488646343128, y: 762.8560198509535), control2: CGPoint(x: 229.01980067419328, y: 758.5790732954121))
        path.addLine(to: CGPoint(x: 232.646022439003, y: 718.2650618851185))
        path.addLine(to: CGPoint(x: 245.00155059549712, y: 752.2114394381665))
        path.addCurve(to: CGPoint(x: 361.2114394381665, y: 636.0015505954972), control1: CGPoint(x: 299.00971822642134, y: 732.5539830629833), control2: CGPoint(x: 341.5539830629833, y: 690.0097182264213))
        path.addLine(to: CGPoint(x: 361.4759939292649, y: 635.2746964679816))
        path.addLine(to: CGPoint(x: 361.70919366001453, y: 634.5371845107745))
        path.addCurve(to: CGPoint(x: 364.6293152668532, y: 624.6465365925144), control1: CGPoint(x: 362.7528350236736, y: 631.2365889986781), control2: CGPoint(x: 363.7248420621724, y: 627.9444706612945))
        path.addCurve(to: CGPoint(x: 374.79163679945674, y: 557.2499517924135), control1: CGPoint(x: 370.2847500091522, y: 604.0254161282841), control2: CGPoint(x: 373.3277390972003, y: 583.2307540084918))
        path.addCurve(to: CGPoint(x: 376.125, y: 471.1269590854645), control1: CGPoint(x: 375.928161481137, y: 537.0792643714874), control2: CGPoint(x: 376.125, y: 519.9928468299313))
        path.addLine(to: CGPoint(x: 376.125, y: 365.5))
        path.closeSubpath()
        return path
    }
}
