#!/usr/bin/env python3
"""Transcribe the saved Icon Composer loop outline, never approximate/redesign it."""
import hashlib
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

root = pathlib.Path(__file__).resolve().parents[1]
assets = root / 'apps/ios/Resources/AppIcon.icon/Assets'
front = assets / 'loop-front-light.svg'
back = assets / 'loop-back-light.svg'
p = ET.parse(front).getroot()[0]
q = ET.parse(back).getroot()[0]
assert p.attrib['d'] == q.attrib['d']
assert p.attrib['transform'] == 'translate(512 512) rotate(-45) translate(-170.0 -365.5)'
assert q.attrib['transform'] == 'translate(512 512) rotate(45) translate(-170.0 -365.5)'
for name, radius in [('center-light.svg', '65.875'), ('center-ring-light.svg', '104.125')]:
    circle = ET.parse(assets / name).getroot()[0]
    assert (circle.attrib['cx'], circle.attrib['cy'], circle.attrib['r']) == ('512', '512', radius)
tokens = re.findall(r'[MLCZ]|-?\d+(?:\.\d+)?', p.attrib['d'])
commands = []
i = 0
while i < len(tokens):
    op = tokens[i]; i += 1
    count = {'M': 2, 'L': 2, 'C': 6, 'Z': 0}[op]
    n = tokens[i:i+count]; i += count
    point = lambda j: f'CGPoint(x: {n[j]}, y: {n[j+1]})'
    if op == 'M': line = f'path.move(to: {point(0)})'
    elif op == 'L': line = f'path.addLine(to: {point(0)})'
    elif op == 'C': line = f'path.addCurve(to: {point(4)}, control1: {point(0)}, control2: {point(2)})'
    else: line = 'path.closeSubpath()'
    commands.append('        ' + line)
text = '''// Generated by scripts/generate-menubar-icon.py from AppIcon.icon. Do not hand-edit.
// Source loop-front-light.svg SHA-256: HASH
import AppKit

/// Native vector template: no Bundle.module lookup or packaging resource dependency.
/// Saved crossed-loop geometry; the original center is solid online, hollow offline.
@MainActor
enum YorozuMenuBarIcon {
    static let size = NSSize(width: 18, height: 18)
    static let connected = makeImage(connected: true)
    static let offline = makeImage(connected: false)

    static func image(connected: Bool) -> NSImage { connected ? self.connected : offline }

    private static func makeImage(connected: Bool) -> NSImage {
        let image = NSImage(size: size, flipped: true) { rect in
            guard let context = NSGraphicsContext.current?.cgContext else { return false }
            draw(in: context, rect: rect, connected: connected)
            return true
        }
        image.isTemplate = true
        return image
    }

    /// Internal for the standalone rendering/geometry regression check.
    static func draw(in context: CGContext, rect: CGRect, connected: Bool) {
        context.saveGState()
        defer { context.restoreGState() }
        context.translateBy(x: rect.minX, y: rect.minY)
        context.scaleBy(x: rect.width / 1024, y: rect.height / 1024)
        // Reduced template coverage also distinguishes offline at 1x, where the hollow
        // center alone is subpixel. macOS still owns the foreground tint.
        context.setFillColor(NSColor.black.withAlphaComponent(connected ? 1 : 0.55).cgColor)
        for angle in [-CGFloat.pi / 4, CGFloat.pi / 4] {
            context.saveGState()
            context.translateBy(x: 512, y: 512)
            context.rotate(by: angle)
            context.translateBy(x: -170, y: -365.5)
            context.addPath(loopPath())
            context.fillPath()
            context.restoreGState()
        }
        // The paper ring is negative space in a monochrome template, not a white paint.
        context.setBlendMode(.clear)
        context.fillEllipse(in: CGRect(x: 407.875, y: 407.875, width: 208.25, height: 208.25))
        context.setBlendMode(.normal)
        let center = CGRect(x: 446.125, y: 446.125, width: 131.75, height: 131.75)
        context.fillEllipse(in: center)
        if !connected {
            context.setBlendMode(.clear)
            // Hollow the existing center; keep both brand loops intact in either state.
            context.fillEllipse(in: center.insetBy(dx: 30, dy: 30))
        }
    }

    private static func loopPath() -> CGPath {
        let path = CGMutablePath()
COMMANDS
        return path
    }
}
'''.replace('HASH', hashlib.sha256(front.read_bytes()).hexdigest()).replace('COMMANDS', '\n'.join(commands))
target = root / 'apps/mac/Sources/YorozuMac/YorozuMenuBarIcon.swift'
if '--check' in sys.argv:
    assert target.read_text() == text, 'Run scripts/generate-menubar-icon.py to refresh the transcription'
else:
    target.write_text(text)
