const $=s=>document.querySelector(s);let state;let inspected=null;
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ProjectX':'1'},body:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw Error(x.error);return x}
function el(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e}
function error(e){$('#error').textContent=e?.message||''}
async function inspect(id){try{inspected=id;const x=await api('/api/context/'+id);for(const t of (x.secretary||[]))for(const k of ['context','decision'])if(t[k])t[k]=JSON.parse(t[k]);for(const t of x.tasks)for(const k of ['secretary_context','delegation'])if(t[k])t[k]=JSON.parse(t[k]);if(x.worker.context){x.worker.bytes=new TextEncoder().encode(x.worker.context).length;x.worker.context=JSON.parse(x.worker.context)}$('#worker-events').replaceChildren(...(x.events||[]).map(e=>{const row=el('article');row.append(el('small',e.kind+' · '+e.source),el('div',e.body,'body'));return row}));if(!(x.events||[]).length)$('#worker-events').append(el('p','No committed worker events received yet. This adapter polls actual visible messages; ephemeral progress may not be available.'));$('#inspect pre').textContent=JSON.stringify(x,null,2);if(!$('#inspect').open)$('#inspect').showModal()}catch(e){error(e)}}
async function refresh(){state=await api('/api/state');$('#backend').textContent=state.adapter;$('#timeline').replaceChildren();$('#turns').replaceChildren();
if(!state.messages.length){const e=el('article','','empty');e.append(el('small','A CLEAN SLATE'),el('h2','Start anywhere.'),el('p','Talk about two projects, return to an old idea, change your mind. It all belongs in one timeline.'));$('#timeline').append(e)}
for(const m of state.messages){const a=el('article','',m.role);a.append(el('strong',m.role==='user'?'You':'PROJECTX'),el('div',m.body,'body'));if(m.result_status==='stale')a.append(el('p','Superseded · an amendment is pending and has NOT been applied','failure'));if(m.status==='pending')a.append(el('p','Received — working in the background; you can keep talking.','pending'));if(m.reply_to){const source=state.messages.find(x=>x.id===m.reply_to);a.append(el('small','↳ '+(source?.body||'Earlier request').slice(0,80)))}if(m.error)a.append(el('p',m.error,'failure'));$('#timeline').append(a);if(m.role==='user'){const row=el('article');row.append(el('p',m.body.slice(0,100)),el('small',`${m.topic} · ${m.reason}`));const b=el('button','Inspect secretary → worker');b.onclick=()=>inspect(m.id);row.append(b);$('#turns').append(row)}}
const selected=$('#mem-topic').value;$('#mem-topic').replaceChildren(new Option('No topic provenance',''),...state.topics.map(t=>new Option(t.label,t.id)));if(selected)$('#mem-topic').value=selected;$('#mem-list').replaceChildren(...state.memory.map(m=>{const row=el('p','↳ '+m.title+' ');const view=el('button','View source');view.onclick=async()=>{try{inspected=null;$('#worker-events').replaceChildren();$('#inspect pre').textContent=JSON.stringify(await api('/api/memory/get',{id:m.id}),null,2);$('#inspect').showModal()}catch(e){alert(e.message)}};row.append(view);const b=el('button','Forget');b.onclick=async()=>{if(!confirm('Delete this memory from Markdown? Original chat history stays unchanged.'))return;try{await api('/api/memory/forget',{id:m.id});await refresh()}catch(e){alert(e.message)}};row.append(b);return row}))}
$('#compose').onsubmit=async e=>{e.preventDefault();error();const b=$('#send');b.disabled=true;b.textContent='Saving…';try{await api('/api/send',{body:$('#body').value});$('#body').value='';await refresh();$('#compose').scrollIntoView({behavior:'smooth',block:'end'})}catch(e){error(e)}finally{b.disabled=false;b.textContent='Send ↗'}};
$('#details').onclick=()=>$('#details-dialog').showModal();$('#memory').onclick=()=>$('#mem-dialog').showModal();document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#mem-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/memory/write',{topic:$('#mem-topic').value||null,title:$('#mem-title').value,body:$('#mem-body').value});$('#mem-title').value='';$('#mem-body').value='';await refresh()}catch(e){alert(e.message)}};
$('#rebuild').onclick=async()=>{try{const x=await api('/api/memory/rebuild',{});await refresh();alert(`${x.count} Markdown notes indexed`)}catch(e){alert(e.message)}};refresh().catch(error);setInterval(()=>{if(!document.hidden){refresh().catch(error);if(inspected&&$('#inspect').open)inspect(inspected)}},1500);
